### ISSUE TITLE
Feature Request: Allow variables in graphite_param/graphite_data

### ISSUE THREAD

**Issue by EricByers** [mailru/graphite-nginx-module#5]
Hello, love the module, and it's been working great for us.

One thing that would make it even better for us, and especially to add custom stats for many locations, would be to allow variables in `graphite_param` and in `graphite_data`.  This would allow us to set a variable in a location and then include something else, instead of having to write out all the graphite_param blocks each time.

It's already possible to do this in the lua chunk just simply because you can concatenate the strings and the nginx variable yourself.

**Comment by kirimedia** [comment]
Hello.

The module aggregates the data of all requests all workers in the shared memory. Shared memory is allocated at the start of nginx. So we need in this moment know how much memory is required.
And that's why necessary to set graphite_data and graphite_param and this it do not get to use nginx variables.
But you can always use the if directive.

```
location /a {
    if ($scheme = http) {
        graphite_data a.http;
    }
    if ($scheme = https) {
        graphite_data a.https;
    }
    ...
}
```

Also graphite_param can be determined only once.

```
location /b {
    graphite_param name=bc.lua aggregate=sum interval=1m;
    content_by_lua '
        ngx.graphite("bc.lua", 1)
    ';
}

location /c {
    content_by_lua '
        ngx.graphite("bc.lua", 1)
    ';
}
```

May be we will support for dynamically defined graphics (graphite_data with nginx variables and graphics from lua without graphite_param), but it will require a significant change in module.
